fragment PaymentFields on PaymentType {
  id
  orderId
  orderNumber
  amount
  currency
  status
  paymentMethod
  authorizeUri
  qrCodeUrl
  expiresAt
}

query Payment($id: String!, $orderNumber: String) {
  payment(id: $id, orderNumber: $orderNumber) {
    ...PaymentFields
  }
}

query PaymentByOrderId($orderId: String!, $orderNumber: String) {
  paymentByOrderId(orderId: $orderId, orderNumber: $orderNumber) {
    ...PaymentFields
  }
}

query BankTransferDetails {
  bankTransferDetails {
    bankName
    accountName
    accountNumber
  }
}

subscription PaymentStatusUpdated($paymentId: String, $orderId: String) {
  paymentStatusUpdated(paymentId: $paymentId, orderId: $orderId) {
    ...PaymentFields
  }
}
