import { createFragmentRegistry } from '@apollo/client/cache';
import {
  SavedAddressFieldsFragmentDoc,
  CartItemFieldsFragmentDoc,
  CartFieldsFragmentDoc,
  OrderItemFieldsFragmentDoc,
  OrderStoreShippingFieldsFragmentDoc,
  OrderShippingAddressFieldsFragmentDoc,
  OrderFieldsFragmentDoc,
  FavoriteProductFieldsFragmentDoc,
  ProductCardFieldsFragmentDoc,
  OrderTrackingFieldsFragmentDoc,
  OrderListFieldsFragmentDoc,
  OrderConfirmationFieldsFragmentDoc,
  PaymentFieldsFragmentDoc,
  SavedPaymentMethodFieldsFragmentDoc,
  ProductDetailFieldsFragmentDoc,
  StorePromotionFieldsFragmentDoc,
  StoreShippingOptionFieldsFragmentDoc,
  StoreFieldsFragmentDoc,
} from '@/lib/graphql/generated/graphql';

/**
 * Auto-generated by scripts/fix-graphql-codegen-duplicates.mjs after codegen.
 * With `dedupeFragments: true`, operation documents keep fragment spreads but
 * omit FragmentDefinitions. Apollo resolves them via this registry.
 */
export const fragmentRegistry = createFragmentRegistry(
  SavedAddressFieldsFragmentDoc,
  CartItemFieldsFragmentDoc,
  CartFieldsFragmentDoc,
  OrderItemFieldsFragmentDoc,
  OrderStoreShippingFieldsFragmentDoc,
  OrderShippingAddressFieldsFragmentDoc,
  OrderFieldsFragmentDoc,
  FavoriteProductFieldsFragmentDoc,
  ProductCardFieldsFragmentDoc,
  OrderTrackingFieldsFragmentDoc,
  OrderListFieldsFragmentDoc,
  OrderConfirmationFieldsFragmentDoc,
  PaymentFieldsFragmentDoc,
  SavedPaymentMethodFieldsFragmentDoc,
  ProductDetailFieldsFragmentDoc,
  StorePromotionFieldsFragmentDoc,
  StoreShippingOptionFieldsFragmentDoc,
  StoreFieldsFragmentDoc,
);
