import type { Metadata } from "next";
import { Mitr } from "next/font/google";
import { AppProviders } from "@/lib/providers";
import "./globals.css";

const mitr = Mitr({
  variable: "--font-mitr",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  display: "swap",
  preload: true,
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${mitr.variable} ${mitr.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-sop-primary-100">
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
